Register form size modified
itsalb3rt/sheiley-shop-app pull request #81
Opened 2022-11-03 02:24 UTC by pcabreram1234

Good night this PR is to resolve the issue describe above.

#75

2022-11-03 21:47 UTC, itsalb3rt requested changes

2022-11-03 21:47 UTC, itsalb3rt commented on src/views/auth/register.vue
> +	.resgiter_container {
Please add a `margin:auto` to centralize the form.

2022-11-04 01:38 UTC, pcabreram1234 commented
I have also applied the changes to resolve the issue #76

2022-11-04 21:57 UTC, itsalb3rt approved these changes
Great work @pcabreram1234

2022-11-04 21:58 UTC, merged